<?php
View::content();


 $css = file_get_contents('css/boot/bootstrap.css');
$number = rand(1,32);


  $html = '
<html>
<head>



<style> 


@page { sheet-size: Letter; }


#example1 {
   //background-image: url(img/frases1/f1.png);;
    background-position: right bottom, left top;
    background-repeat: no-repeat, repeat;
   
    
}

td {


  padding:2px;
}


</style>


</head>
<body>

<div id="example1">
<br />

<div id="nombre" style="margin-left:670px; padding-top:14px;">
<h6>'.$date.'</h6>
</div>

<div id="nombre" style="margin-left:474px; padding-top:38px;">
<h6>'.$paciente->nombreP.'</h6>
</div>

<div id="apellido" style="margin-left:474px; padding-top:1px;">
<h6>'.$paciente->apellidoP.'</h6>
</div>

<div id="fecha" style="margin-left:703px; padding-top:-50px;">
<h6>'.$paciente->rhP.'</h6>
</div>


<div id="fecha" style="margin-left:703px; padding-top:4px;">
<h6><small>'.$paciente->celP.'</small></h6>


</div>


<div id="medicamentos" style="margin-left:40px; padding-top:77px; padding-bottom:105px;   ">';

for ($i=0; $i <count($e) ; $i++) { 
 $html.=''.$e[$i].'<br>';

}



$html.='</div>



</div>

</body>
</html>
';





$html2='<br> <br>';
 

Load::lib('pdf/mpdf');

   //   $mpdf = new mPDF('utf-8', array(896,477));

 $mpdf = new mPDF('c','', 0, '', '0', '0', '0', '0', '0', '0', 'Letter');
 //$mpdf = new mPDF('utf-8', 'Letter-L');


    $html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
    $html2 = mb_convert_encoding($html2, 'UTF-8', 'UTF-8');
    $mpdf->WriteHTML($css, 1);
   


    $mpdf->WriteHTML($html);
   

  
   $string = 'formulaMedicamentos'.$paciente->nombreP.$paciente->apellidoP.$date.'.pdf';
  
  
    
    $mpdf->Output($string, 'I');

exit;

 
// añadir vaciar tabla mysql codigo 
    ?>
