<?php
View::content();





 $css = file_get_contents('css/boot/bootstrap.css');
$number = rand(1,32);


  $html = '
<html>
<head>



<style> 

@page { sheet-size: Letter; }






#example1 {
       background-image: url(img/frases1/f'.$number.'.png);;
    background-position: right bottom, left top;
    background-repeat: no-repeat, repeat;
    width:796px;
    height:480px;
    
}




</style>


</head>
<body>

<div id="example1">

<div id="nombre" style="margin-left:442px; padding-top:79px;">
<h5>'.$paciente->nombreP.'</h5>
</div>

<div id="apellido" style="margin-left:442px; padding-top:1px;">
<h5>'.$paciente->apellidoP.'</h5>
</div>

<div id="fecha" style="margin-left:660px; padding-top:-54px;">
<h5>'.$date.'</h5>
</div>


<div id="fecha" style="margin-left:660px; padding-top:-2px;">
<h5>'.$paciente->celP.'</h5>
</div>


<div id="medicamentos" style="margin-left:40px; padding-top:72px; padding-bottom:105px;   ">

<table class="table" style="width:19cm;  "  autosize="1">
  <thead>
    <tr>
      <th>Cant</th>
      <th>Descripción</th>
      <th>Forma Farmacéutica</th>
      <th>Posología</th>
    </tr>
  </thead>
  <tbody>';

  $listaAnadidos=$_SESSION['listaAnadidos'];

for ($i=0; $i <count($listaAnadidos) ; $i++) { 
 $html.='<tr><td> '.$listaAnadidos[$i]->cM .'</td>';
 $html.='<td>'.$listaAnadidos[$i]->dM .'</td>';
 $html.='<td>'.$listaAnadidos[$i]->fM .'</td>';
 $html.='<td>'.$listaAnadidos[$i]->nM .'</td></tr>';
}



   
  $html.='</tbody>
</table>


</div>



</div>

</body>
</html>
';





$html2='<br> <br>';

Load::lib('pdf/mpdf');

   //   $mpdf = new mPDF('utf-8', array(896,477));

 $mpdf = new mPDF('c','', 0, '', '0', '0', '0', '0', '0', '0', 'A4');
 //$mpdf = new mPDF('utf-8', 'Letter-L');


    $html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
    $html2 = mb_convert_encoding($html2, 'UTF-8', 'UTF-8');
    $mpdf->WriteHTML($css, 1);
   


    $mpdf->WriteHTML($html);
   

  
  
    
    $mpdf->Output('formulaManual.pdf', 'I');

exit;

 
// añadir vaciar tabla mysql codigo 
    ?>
