<?php View::content();  // Profesores Terminado?>

<div class="row">

    <div class="col-lg-2">
        <div class="actions">
            <?= Html::linkAction("crear/", 'Crear nuevo medicamento', 'class="btn btn-primary"') ?>
        </div>
    </div>

    <div class="col-lg-2" style="margin-left:30px;">
        <div class="actions">
            <?= Html::linkAction("buscar/", 'Buscar medicamento', 'class="btn btn-info"') ?>
        </div>
    </div>

     <div class="col-lg-2" style="margin-left:30px;">
        <div class="actions">
            <?= Html::linkAction("listar/", 'Listar Medicamentos', 'class="btn btn-danger"') ?>
        </div>
    </div>
</div>

<hr>

<!-- /.row -->

        <h4>Últimos medicamentos registrados... </h4>
        <hr>
        <div class="row">

            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead class="thead-inverse">
                            <tr>
                                <th>No</th>
                                <th>Nombre ó Descripción</th>
                                <th>Forma Farmacéutica</th>
                                <th>Posología</th>
                                <th>Precio ($)</th>
                                <th>Descuento (0 - 100)%</th>
                               
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php for($i=0; $i<count($listaPacientes); $i++) { ?>
                                    <tr>
                                       <td><?php echo ($i+1) ?></td>
                                        <td><b><?php echo $listaPacientes[$i]->descripcionM ?><b></td>
                                        <td><?php echo $listaPacientes[$i]->formaFarmaM ?></td>
                                        <td><?php echo $listaPacientes[$i]->necesidadM ?></td>
                                        <td><?php echo $listaPacientes[$i]->precio ?></td>
                                        <td><?php echo $listaPacientes[$i]->descuento ?></td>

                                        <?php 

                                         $idMedicamento = $listaPacientes[$i]->idMedicamento;

                                        ?>

                                        <td>
                                        <i class="fa fa-fw fa-edit"></i><?php echo Html::linkAction("edit/$idMedicamento", ' Editar Medicamento') ?>

                                           
                                        </td>  
                                    </tr>
                                 <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <!-- /.row -->
