<?php
View::content();



  $css = file_get_contents('css/bootstrap.css');


 

$number = rand(1,35);

  $html = '
<html>
<head>



<style> 

@page { sheet-size: Letter;



 }

 table {
	border-collapse: separate;

	padding: 3px;
	margin: 0px 10px 0px 10px;
	empty-cells: hide;
	
}

#example1 {
       background-image: url(img/test.png);;
    background-repeat: no-repeat, repeat;
    width:100%;
    height:100%;
    margin-left:5px;
    
}



</style>


</head>
<body>
<div id ="example1">

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<br>
<br>

<h4 style ="text-align:center;"> Lista de Medicamentos </h4>


<div id="medicamentos" style="margin-left:40px; padding-top:52px; padding-bottom:105px;   ">

<table style="overflow: autohiddenvisible	wrap" class="table table-striped" style="width:19cm;  "  autosize="1">
  <thead>
    <tr>
      <th>Cant</th>
      <th>Descripción</th>
      <th>Forma Farmacéutica</th>
      <th>Necesidad</th>
       <th>Precios</th>
    </tr>
  </thead>
  <tbody>';



for ($i=0; $i <count($listaAnadidos) ; $i++) { 
 $html.='<tr><td> '.($i+1) .'</td>';
 $html.='<td>'.$listaAnadidos[$i]->descripcionM .'</td>';
 $html.='<td>'.$listaAnadidos[$i]->formaFarmaM .'</td>';
  $html.='<td>'.$listaAnadidos[$i]->necesidadM .'</td>';
 $html.='<td>'.$listaAnadidos[$i]->precio .'</td></tr>';
}



   
  $html.='</tbody>
</table>


</div>



</div>
</div>
</body>
</html>
';





$html2='<br> <br>';
 
Load::lib('pdf/mpdf');

   //   $mpdf = new mPDF('utf-8', array(896,477));

$mpdf=new mPDF('c','Letter','','',1.5,1.5,10,18,16,13); 

$mpdf->SetDisplayMode('fullpage');

$mpdf->list_indent_first_level = 0;	// 1 or 0 - whether to indent the first level of a list
 //$mpdf = new mPDF('utf-8', 'Letter');


    $html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
    $html2 = mb_convert_encoding($html2, 'UTF-8', 'UTF-8');
    $mpdf->WriteHTML($css, 1);
   

     $mpdf->WriteHTML($html);
  

    
    $mpdf->Output('listaMedicamentosCompleta.pdf', 'I');

exit;

 
// añadir vaciar tabla mysql codigo 
    ?>
