<?php View::content();  // Profesores Terminado?>

<div class="row">

    <!--<div class="col-lg-3">
        <div class="actions">
            <?= Html::linkAction("create/", 'Crear nuevo procedimiento', 'class="btn btn-primary"') ?>
        </div>
    </div>-->

    <div class="col-lg-2">
        <div class="actions">
            <?= Html::linkAction("buscar/", 'Buscar procedimiento', 'class="btn btn-info"') ?>
        </div>
    </div>
</div>

<hr>

<!-- /.row -->
<div class="row">
    <div class="col-lg-2">
        <?php if ($listaProcedimientos->prev) echo Html::linkAction("index/$listaProcedimientos->prev/", '<< Anterior'); ?>
    </div>
    <div class="col-lg-2">
        <?php if ($listaProcedimientos->next) echo Html::linkAction("index/$listaProcedimientos->next/", 'Próximo >>'); ?>
    </div>
</div>

<!-- /.row -->


<h4>Lista de Procedimientos Actuales...</h4>
<hr>
<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Título</th>
                        <th>Medicamentos</th>
   
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($listaProcedimientos->items as $item) : ?>
                        <tr>
                            <td><?php echo $item->idTipo ?></td>
                            <td><?php echo $item->tituloTipo ?></td>
                                                       
                            
                            <td>
                                <i class="fa fa-fw fa-edit"></i><?php echo Html::linkAction("edit/$item->idTipo", ' Editar') ?>

                                  <i class="fa fa-fw fa-edit"></i><?php echo Html::linkAction("verProcedimientos/$item->idTipo", ' Ver medicamentos') ?>
                               
                            </td>  
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

</div>
<!-- /.row -->
