<br />

<div class="well">

    <h3>Contacto</h3>

    <p>
        Pitalito- Huila
        <br />
        Dirección: Carrera 1B # 6-33
        <br/>
        Barrio: Agua Blanca
        <br />
        Teléfono: 3134539588
       
    </p>
    <div >

<?php

$number = rand(0,2);

$frases = array('"Nuestra recompensa se encuentra en el esfuerzo y no en el resultado. Un esfuerzo total es una victoria completa."','"Al final, lo que importa no son los años de la vida, si no la vida de los años". ','"La vida no se ha hecho para comprenderla, sino para vivirla."')

 ?>
    <h4><b><?php echo $frases[$number]; ?></b></h4>
    </div>
</div>