<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/Clinic/inicio" style ="font-size:23px">Bienvenido a Clinic</a>
    </div>
    
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        <li class="dropdown">
            <?php
            $usuario = Auth::get('usuario');
            if ($usuario != null) {
                ?>
                <a style ="font-size:17px" href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $usuario; ?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a style ="font-size:15px" href="/Clinic/usuarios/sesion"><i class="fa fa-fw fa-power-off"></i> Cerrar Sesión</a>
                    </li>
                </ul>
            <?php } ?> 
        </li>
    </ul>
    
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li>
                <a href="/Clinic/inicio"style ="font-size:18px"><i class="fa fa-fw fa-ambulance"></i> Inicio</a>
            </li>
            <?php
            $tipo = Auth::get('rol');
            if ($tipo != null && $tipo == 1) {
                ?>
                
                <li>
                    <a style ="font-size:18px" href="/Clinic/pacientes/" id="Registro_Profesor"><i class="fa fa-fw fa-hospital-o"></i> Gestionar Pacientes</a>
                </li>

                <li>
                    <a style ="font-size:18px" href="/Clinic/procedimientos"><i class="fa fa-fw fa-stethoscope"></i> Procedimientos</a>
                </li>

                <li>
                    <a style ="font-size:18px" href="/Clinic/medicamentos"><i class="fa fa-fw fa-medkit"></i> Medicamentos</a>
                </li>

                 <li>
                    <a style ="font-size:18px" href="/Clinic/citas/verCalendario"><i class="fa fa-fw fa-book"></i> Citas</a>
                </li>
				
				<li>
                    <a style ="font-size:18px" href="/Clinic/contabilidad/"><i class="fa fa-fw fa-bar-chart"></i> Contabilidad</a>
                </li>


                 <li>
                    <a style ="font-size:18px" href="/Clinic/creditos"><i class="fa fa-fw fa-cc-visa"></i> Créditos</a>
                </li>

                 <li>
                    <a style ="font-size:18px" href="javascript:;" data-toggle="collapse" data-target="#demo4"><i class="fa fa-fw fa-stack-overflow"></i> Historias Clinicas<i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="demo4" class="collapse">
                        <li>
                            <a style ="font-size:17px"  href="/Clinic/historiaclinica/buscar">Asignar a Paciente</a>
                        </li>
                        <li>
                            <a style ="font-size:17px" href="/Clinic/historiaclinica/index">Listar todas </a>
                        </li>
                   
                     
                      
                    </ul>
        </li>
                


                <li>
                    <a style ="font-size:18px" href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-download"></i> Imprimibles<i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="demo" class="collapse">


                        <li>
                            <a style ="font-size:17px"  href="/Clinic/formula/index">Fórmulas</a>
                        </li>
                    
					    <li>
                            <a style ="font-size:17px"  href="/Clinic/certificaciones/">Certificaciones</a>
                        </li>

                        <li>
                            <a style ="font-size:17px"  href="/Clinic/remision/">Remisiones</a>
                        </li>

                         <li>
                            <a style ="font-size:17px"  href="/Clinic/remision/reciboCaja"> Recibos de Caja</a>
                        </li>

                    
                        
                     
                      
                    </ul>
                </li> <!-- Fin Lista Desplegable Generables -->


               

                <?php } else {
                    if($tipo == 2) { ?>
                    <li>
                        <a style ="font-size:17px" href="/Clinic/nota"><i class="fa fa-fw fa-pencil"></i> Medicamentos</a>
                    </li>
                    <?php }
                } ?>
                 <li>
                    <a style ="font-size:18px"href="/Clinic/creditos/copiaSeguridad"><i class="fa fa-fw fa-refresh"></i> Copia de Seguridad</a>
                </li>

                 <li>
                    <a style ="font-size:18px"href="/Clinic/inicio/acerca"><i class="fa fa-fw fa-info-circle"></i> Acerca de</a>
                </li>
           
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>