<?php View::content(); ?>

<?php echo Form::open("formula/generarFormulaE"); ?>

<h4><b>Introduza los exámenes en orden por favor </b></h4>
<hr>

<div class="row">
<div class="col-lg-6">
<div class="panel panel-primary">
  <div class="panel-heading">Formulando a :  </div>
  <div class="panel-body"><?php echo $paciente->nombreP."&nbsp".$paciente->apellidoP; ?></div>
</div>
</div>
</div>


<div class="row">


<div class="col-lg-4">
   <div class="form-group">
  <label for="comment">Exámenes a tomar<br> <small>!!!!No olvides añadir el guión al final del renglón</small></label>
  <input type="hidden" name ="idPaciente" id="idPaciente" value ="<?php echo $paciente->idPaciente; ?>">

  <textarea class="form-control" rows="8" id="exams" name ="exams" placeholder ="1. Examen de sangre- 
2. Examen conteo de plaquetas-
3. Examen tejido muscular- 
4. Examen 4-
5. Examen 5-
6. Examen 6-
7. Examen 7-
8. Examen 8-

" required></textarea>
</div>

</div>


<div class="col-lg-4">
   <div class="form-group">
  <label for="comment"> <br>Ejemplo de como se deben llenar los exámenes: </label>
  <textarea class="form-control" rows="8" id="des" name ="des" placeholder ="1. Examen de sangre- 
2. Examen conteo de plaquetas-
3. Examen tejido muscular-
4. Examen 4-
5. Examen 5-
6. Examen 6-
7. Examen 7-
8. Examen 8-

" disabled=""></textarea>
</div>

</div>



</div>


<hr>



<div class="row">


  <div class="col-lg-3">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar">Generar fórmula de exmanes
            
        </button>
    </div>
<?php echo Form::close(); ?>

    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

