<?php View::content(); ?>


<div class="row">

    <div class="col-lg-3">
        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open(); ?>
                <h4>Nombre ó descripción</h4>
                <input type="hidden" name="valN" id ="valN" value="2">
                <input type="text" name="nombreP" id ="nombreP" class="form-control" placeholder="Introducir Nombre" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>
    </div>



</div>

<!-- /.row -->
<hr>


<!-- /.row -->

<br>

<h4>Lista Medicamentos</h4>
<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
             <thead class="thead-inverse">
                <tr>
                    <th>No</th>
                    <th>Nombre ó Descripción</th>
                    <th>Forma Farmacéutica</th>
                    <th>Necesidad</th>
                    <th>Precio ($)</th>

                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php for($i=0; $i<count($listaPacientes); $i++) { ?>
                <tr>
                 <td><?php echo $listaPacientes[$i]->idMedicamento ?></td>
                 <td><b><?php echo $listaPacientes[$i]->descripcionM ?><b></td>
                 <td><?php echo $listaPacientes[$i]->formaFarmaM ?></td>
                 <td><?php echo $listaPacientes[$i]->necesidadM ?></td>
                 <td><?php echo $listaPacientes[$i]->precio ?></td>

                 <?php 

                 $idMedicamento = $listaPacientes[$i]->idMedicamento;

                 ?>

                 <td>

                   <?php echo Form::open("formula/guardarMedicamentos/"); ?>

                    <input type="hidden" name="idMedicamento" id ="idMedicamento" value="<?php echo $idMedicamento; ?>">

                       <input type="number" min="1" name="cantidad" id ="cantidad" placeholder ="Cantidad ..." required>
                       <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar">Añadir Medicamento
                       
                    </button>
                    <?php echo Form::close(); ?>



                </td>  
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
</div>

</div>
<!-- /.row -->
<!-- /.row -->

<div class="row">

    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->
