<?php
View::content();


 $css = file_get_contents('css/boot/bootstrap.css');
$number = rand(1,32);


  $html = '
<html>
<head>



<style> 


@page { sheet-size: Letter; }


#example1 {
    background-image: url(img/LogoVendoExpress200.jpg);
    background-position: right bottom, left top;
    background-repeat: no-repeat, repeat;
    width:200px;
    height:127px;
    
}

td {


  padding:2px;
}


</style>


</head>
<body>

<div id="example1"></div>





<div id="nombre" style="margin-left:480px; padding-top:16px;">
<h5>'.number_format($monto).'</h5>
</div>

<div id="apellido" style="margin-left:480px; padding-top:1px;">
<h5>'.$nit.'</h5>
</div>

<div id="fecha" style="margin-left:700px; padding-top:-54px;">
<h5>'.$city.' '.$fecha.'</h5>
</div>


<div id="fecha" style="margin-left:700px; padding-top:2px;">
<h6>'.$recibidoDe.'</h6>
</div>


<div id="fecha" style="margin-left:0px; padding-top:2px;">
<h6>'.$dir.'</h6>
</div>

<div id="apellido" style="margin-left:480px; padding-top:0px;">
<h5>'.$tel.'</h5>
</div>

<div id="apellido" style="margin-left:0px; padding-top:0px;">
<h5>'.$suma.'</h5>
</div>





<div id="fecha" style="margin-left:700px; padding-top:0px;">
<h6>'.$concepto.'</h6>
</div>





';





$html2='<br> <br>';
 

Load::lib('pdf/mpdf');

   //   $mpdf = new mPDF('utf-8', array(896,477));

 //$mpdf = new mPDF('c','Letter');
 $mpdf = new mPDF('utf-8', 'Letter-L');


    $html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
    $html2 = mb_convert_encoding($html2, 'UTF-8', 'UTF-8');
    $mpdf->WriteHTML($css, 1);
   


    $mpdf->WriteHTML($html);
   

  
   $string = 'formulaMedicamentos'.$paciente->nombreP.$paciente->apellidoP.$date.'.pdf';
  
  
    
    $mpdf->Output($string, 'I');

exit;

 
// añadir vaciar tabla mysql codigo 
    ?>
