<?php View::content();  // Profesores Terminado?>



<hr>

<!-- /.row -->

<h4>Listando pacientes encontrados...</h4>
<hr>
<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
                 <thead class="thead-inverse">
                    <tr>
                        <th>No</th>
                        <th>Cédula</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php for($i=0; $i<count($listaCreditos); $i++) { ?>
                    <tr>
                     <td><?php echo $listaCreditos[$i]->idPaciente ?></td>
                     <td><b><?php echo $listaCreditos[$i]->cedulaP ?><b></td>
                     <td><?php echo $listaCreditos[$i]->nombreP ?></td>
                     <td><?php echo $listaCreditos[$i]->apellidoP ?></td>
                     <?php

                         $idPaciente = $listaCreditos[$i]->idPaciente;
                         $d = $listaCreditos[$i]->hasCredito;
                      ?>
                     <td>
                            <i class="fa fa-fw fa-money"></i><?php 

                            if ($d!=1) 
                            {

                              echo Html::linkAction("crear/$idPaciente", ' Crear Crédito','class="btn btn-primary"');
                            }

                            else
                             {   echo Html::linkAction("ver/$idPaciente", ' Ver Crédito','class="btn btn-warning"');

                             }

                      ?>


                  </td> 

                


                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

</div>
<!-- /.row -->


<hr>

<div class="row">


    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>