<?php View::content(); ?>

<?php echo Form::open(); ?>

<h4><b>Información del crédito a EDITAR </b></h4>
<hr>

<div class="row">
<div class="panel panel-primary">
  <div class="panel-heading">Crédito Actual para el paciente: <?php echo $paciente->nombreP."&nbsp".$paciente->apellidoP; ?> </div>
  <div class="panel-body">Deuda Actual: <b><?php $c=number_format($credito->deuda); echo $c; ?></b> pesos</div>
</div>
</div>

<div class="row">


<div class="col-lg-6">
   <div class="form-group">
  <label for="comment">Descripción de la deuda</label>
  <textarea class="form-control" rows="6" id="des" name ="des" required><?php echo $credito->des;?></textarea>
</div>

</div>

</div>



<div class="row">

<div class="col-lg-3">
   <div class="form-group">
  <label for="comment">Introduzca el valor del crédito en ($) pesos</label>
  <input class="form-control" type="number" name ="both" id="both" required min ="0" >
  <input  type="hidden" name ="valVayne" id="valVayne" value="2">
</div>
</div>






</div>
<!-- /.row -->

<div class="row">

<div class="col-lg-8">
<h4></h4>
   <div class="form-group">
  <label for="asda">Escoja si el monto será Abono o Aumento de deuda:</label><br>
  <label class="radio-inline"><input type="radio" id ="tipoMonto" name="tipoMonto" value="1">Abono</label>
 <label class="radio-inline"><input type="radio" id ="tipoMonto" name="tipoMonto" value ="2" checked>Aumento de deuda</label>
  
</div>



</div>
</div>
<hr>




<div class="row">


  <div class="col-lg-2">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar">ActualizarCrédito
            
        </button>
    </div>


    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close(); ?>