<?php View::content();  // Profesores Terminado?>



<hr>

<!-- /.row -->

<h4>Visor de créditos</h4>
<hr>
<div class="row">

  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered table-hover table-striped">
        <thead class="thead-inverse">
          <tr>
            <th>No</th>
            <th>Cédula</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Descripción deuda</th>
            <th>Fecha Creación</th>
            <th>Fecha Última Modificación</th>
            <th>Total deuda</th>
            <th>Acciones</th>


          </tr>
        </thead>
        <tbody>
          <?php for($i=0; $i<count($listaCreditos); $i++) { ?>
          <tr>
           <td><?php echo $listaCreditos[$i]->idCredito ?></td>
           <td><b><?php echo $listaCreditos[$i]->cedulaP ?><b></td>
           <td><?php echo $listaCreditos[$i]->nombreP ?></td>
           <td><?php echo $listaCreditos[$i]->apellidoP ?></td>
           <td><?php echo $listaCreditos[$i]->des ?></td>
           <td><?php echo $listaCreditos[$i]->fecha ?></td>
           <td><?php echo $listaCreditos[$i]->fechaMod ?></td>
           <td><?php echo number_format($listaCreditos[$i]->deuda) ?></td> 
           <?php 

           $idCredito = $listaCreditos[$i]->idCredito;
           ?>
           <td>

            <i class="fa fa-fw fa-edit"></i><?php 



            echo Html::linkAction("edit/$idCredito", 'Editar Crédito');

            ?>


          </td>  






        </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
</div>

</div>




<div class="row">


 

    <div class="col-lg-3">
        <div class="actions">
            <?= Html::linkAction("", 'Volver al menú principal', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->
