<!-- Page Acerca De -->
<div class="jumbotron">
    <h3>Clinic fué desarrollado por : Ing. Yeison E. Caicedo </h3>
    <h4>Si encuentra algún problema por favor contactarse al siguiente correo electónico :</h4>
   
        
        
        <h4 style="color:#00BFFF;">yecaicedo@unicauca.edu.co</h4>
        <h4>Celular : 312-666-5895</h4>
        <h4>Versión Actual de Clinic: 1.0</h4>
        
        <h4>Año: 2017</h4>
         <br />
    </p>
</div>
