<?php View::content(); ?>

<?php echo Form::open(); ?>

<div class="row">

    <div class="col-lg-5">
        <div class="panel panel-success ">
            <div class="panel-heading"><b>Creando</b> la historia Clinica del siguiente paciente: </div>
            <div class="panel-body"><b><?php echo $paciente->nombreP; echo "&nbsp;"; echo $paciente->apellidoP; ?></b></div>
        </div>
    </div>
</div>


<h4>Creemos la historia Clinica  </h4>
<hr>

<div class="row">

    <div class="col-lg-8">
        <div class="form-group">
            <label for="idProF">Motivo Principal de la consulta(Crear una historia por cada cita)</label>

            <textarea name="motivoH" maxlength="10000" id="motivoH" rows="7" class="form-control" placeholder="Dolores- Trastornos - Enfermedades crónicas- Etc...    Escriba aquí el porqué el paciente está en consulta....Máx 10000 Palabras"></textarea> 
            
            <input type="hidden" name="valN" id="valN" class="form-control" value ="2" > 
      
        </div>
    </div>
    </div>
    <h4>Datos del paciente: </h4>
    <hr>
    <div class="row">
 

    <div class="col-lg-3">
        <div class="form-group">
            <label for="nombreF">Presión Sistólica</label>
            <input type="text" name="preSistolica"  id="preSistolica" placeholder ="Ronda los 120 mm/Hg"class="form-control"  
             required>
        </div>
    </div>
  
   

    <div class="col-lg-3">

        <div class="form-group">
            <label for="apellidoF">Presión Diastólica </label>
            <input type="text" name="preDiastolica"  id="preDistolica" placeholder ="Ronda los 80 mm/Hg" class="form-control" 
                
            required>
        </div>
    </div>
   



    <div class="col-lg-3">

        <div class="form-group">
            <label for="celularF">Frecuencia Cardiaca (L/M)</label>
            <input type="text" name="frecCardiaca" id="frecCardiaca" placeholder="Latidos/Minuto" class="form-control"
             required>
        </div>
    </div>


       <div class="col-lg-3">

        <div class="form-group">
            <label for="celularF">Frecuencia Respiratoria (R/M)</label>
            <input type="text" name="frecRespiratoria" id="frecRespiratoria" placeholder="Respiraciónes/Minuto" class="form-control"
             required>
        </div>
    </div>
    
</div>
<hr>

<div class="row">

    <div class="col-lg-4">
    <div class="form-group">
            <label for="fecha">Fecha para historia actual</label>
            <input type="date" name="fechaNueva" id="fechaNueva" 
                
                 class="form-control"
             required>
        </div>
            
    </div>


</div>

<!-- SEGUNDA COLUMMNA -->

<hr>

<div class="row">

    <div class="col-lg-2">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar">Guardar Historia
            <!--?php echo Form::submit("Ingresar","class: boton"); ?-->
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close(); ?>