<?php
View::content();


  $css = file_get_contents('css/bootstrap.css');

  function formatSpanishString($str) {
    $firstLetter = mb_strtoupper(mb_substr($str, 0, 1));
    $restOfString = mb_strtolower(mb_substr($str, 1));

    // Replace any accented uppercase letters with their lowercase counterparts.
    $restOfString = mb_strtolower(preg_replace('/[\p{Lu}ÁÉÍÓÚÜ]/u', '\\0', $restOfString));
    
    return $firstLetter . $restOfString;
}

 

$number = rand(1,35);

  $html = '
<html>
<head>


<style> 

@page { sheet-size: Letter;


 }

 table {
	border-collapse: separate;

	padding: 3px;
	margin: 0px 10px 0px 10px;
	empty-cells: hide;
	
}

#example1 {
    background-image: url(img/historiaFinal.png);
    background-repeat: no-repeat, repeat;
    width:100%;
    height:100%;
    margin-left:5px;
    
}

.m_title {
  display:block;
  padding-left: 10px;
}


.date {
  font-size: 13px;
  margin-right: 10px;
}

td.date {
  padding: 10px;
}


</style>


</head>
<body>
<div id ="example1">

<div id ="consultorio">


<div id="nombre" style="margin-left:405px; padding-top:67px;">
<h5>Nombre: '.$paciente->nombreP.'</h5>
</div>

<div id="apellido" style="margin-left:405px; padding-top:1px;">
<h5>Apellido: '.$paciente->apellidoP.'</h5>
</div>

<div id="fecha" style="margin-left:405px; padding-top:-1px;">
<h5>Celular: '.$paciente->celP.'</h5>
</div>


</div>




<br>
<br>
<br>

<br>
<br>
<br>
<br>

<h5 style ="text-align:center;"> Historias Clinicas  </h5>


<div id="medicamentos" style="margin-left:40px; padding-top:35px; padding-bottom:105px;   ">

<table style="overflow: autohiddenvisible	wrap" class="table table-striped" style="width:19cm;  "  autosize="1">
  <thead>
    <tr>
       <th>Fecha</th>
       <th>  </th>
      <th>Motivo Consulta</th>
      <th>P.Sistólica</th>
      <th>P.Distólica</th>
       <th>Frecuencia Cardiaca</th>
      <th>Frecuencia Respiratoria</th>
    </tr>
  </thead>
  <tbody>';



for ($i=0; $i <count($listaClinicas) ; $i++) { 
   $html.='<tr><td class="date"> '.$listaClinicas[$i]->fecha .'</td>';
    $html.='<td>&nbsp;</td>';
 $html.='<td class="m_title"> '. formatSpanishString($listaClinicas[$i]->motivoH) .'</td>';
 $html.='<td>'.$listaClinicas[$i]->preSistolica .'</td>';
 $html.='<td>'.$listaClinicas[$i]->preDistolica .'</td>';
 $html.='<td>'.$listaClinicas[$i]->frecCardiaca .'</td>';
 $html.='<td>'.$listaClinicas[$i]->frecRespiratoria .'</td></tr>';
}



   
  $html.='</tbody>
</table>


</div>



</div>
</div>
</body>
</html>
';





$html2='<br> <br>';
 
Load::lib('pdf/mpdf');

   //   $mpdf = new mPDF('utf-8', array(896,477));

$mpdf=new mPDF('c','Letter','','',1.5,1.5,10,18,16,13); 

$mpdf->SetDisplayMode('fullpage');

$mpdf->list_indent_first_level = 0;	// 1 or 0 - whether to indent the first level of a list
 //$mpdf = new mPDF('utf-8', 'Letter');


    $html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
    $html2 = mb_convert_encoding($html2, 'UTF-8', 'UTF-8');
    $mpdf->WriteHTML($css, 1);
   


    $mpdf->WriteHTML($html);
   if ($f1==1 and $f2==1) {
     $fechas="Completa";
   }else{

    $fechas=$f1.'&'.$f2;
   }
  $string = 'historiaClinica'.$paciente->nombreP.$paciente->apellidoP.$fechas.'.pdf';
  
  
    
    $mpdf->Output($string, 'I');

exit;


 
// añadir vaciar tabla mysql codigo 
    ?>
 