<?php
View::content();

 $css = file_get_contents('css/boot/bootstrap.css');

  $html = '
<html>
<head>



<style> 


@page { sheet-size: Letter; }


#example1 {
       background-image: url(img/fondoBlancoCarta.png);;
    background-position: right bottom, left top;
    background-repeat: no-repeat, repeat;
 
    
    
}




</style>


</head>
<body>

<div id="example1">

<div id="nombre" style="margin-left:405px; padding-top:67px;">
<h5></h5>
</div>

<div id="apellido" style="margin-left:405px; padding-top:1px;">
<h5></h5>
</div>

<div id="fecha" style="margin-left:405px; padding-top:-1px;">
<h5></h5>
</div>


<div id="fecha" style="margin-left:676px; padding-top:-2px;">
<h5></h5>
</div>


<div id="medicamentos" style="margin-left:40px; padding-top:172px; padding-bottom:105px;   ">
<h5 style="text-align:center; margin-left:-30px;"><center>Lista de Registros desde :'.$fechaInicial.' hasta '.$fechaFinal.'</center></h5>
<h5 style="text-align:center; margin-left:-40px;"><center>Saldo Total :'.number_format($sumaTotal).' pesos.</center></h5>
<hr>

<table class="table" style="width:19cm;  "  autosize="1">
  <thead>
    <tr>
      <th>#</th>
      <th>Fecha</th>
      <th>Concepto</th>
      <th>Valor</th>
       <th>Tipo</th>
    
    </tr>
  </thead>
  <tbody>';



for ($i=0; $i <count($listaRegistros) ; $i++) { 

  if ($listaRegistros[$i]->tipoIngEgre=="Entrada"){
    $class="success";
  }else{

    $class="warning";
  }
   $html.='<tr><td class="success"> '.($i+1).'</td>';
 $html.='<td class="'.$class.'"> '.$listaRegistros[$i]->fecha .'</td>';
 $html.='<td class="'.$class.'">'.$listaRegistros[$i]->concepto .'</td>';
 $html.='<td class="'.$class.'">'.number_format($listaRegistros[$i]->monto) .'</td>';
 $html.='<td class="'.$class.'">'.$listaRegistros[$i]->tipoIngEgre .'</td></tr>';
}



   
  $html.='</tbody>
</table>


</div>



</div>

</body>
</html>
';







Load::lib('pdf/mpdf');

   //   $mpdf = new mPDF('utf-8', array(896,477));

 //$mpdf = new mPDF('c','Letter');
 $mpdf = new mPDF('utf-8', 'Letter');


    $html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
    
    $mpdf->WriteHTML($css, 1);
   


    $mpdf->WriteHTML($html);
  
  $string = 'informeContablefechas'.$fechaInicial.'-'.$fechaFinal.'.pdf';
  
  
    
    $mpdf->Output($string, 'I');

        exit;

 

    ?>
