<?php View::content();  // Profesores Terminado ?>



<hr>

<hr>

<h4>Opción Adicional</h4>

 <?php   echo Html::linkAction("imprimirInformeContable", 'Generar PDF ','class="btn btn-primary"'); ?>

<hr>

<hr>

<!-- /.row -->

<h4>Listando los registros entre: <b> <?php echo $fecha1; ?></b> y <b><?php echo $fecha2; ?></b></h4>
<h4>Orden: Ascendente</h4>
<h4 style="color:#f05545">Saldo total : <?php echo number_format($saldoFinal);?> pesos</h4>
<hr>
<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Fecha (Año-Mes-Día)</th>
                        <th>Concepto</th>
                        <th>Valor ($)</th>
                        <th>Tipo</th>
                        <th>Acciones</th>
                       
                       
                    </tr>
                </thead>
                <tbody>
                    <?php for($i=0; $i<count($listaCreditos); $i++) {
                        
                        if($listaCreditos[$i]->tipoIngEgre=='Entrada'){
                            $class="success";
                        }else{

                            $class="warning";
                        }
                         ?>
                    <tr>
                     <td class="<?php echo $class; ?>"><?php echo $listaCreditos[$i]->id ?></td>
                     <td class="<?php echo $class; ?>"><b><?php echo $listaCreditos[$i]->fecha ?><b></td>
                     <td class="<?php echo $class; ?>"><?php echo $listaCreditos[$i]->concepto ?></td>
                     <td class="<?php echo $class; ?>"><?php echo $listaCreditos[$i]->monto ?></td>
                     <td class="<?php echo $class; ?>"><?php echo $listaCreditos[$i]->tipoIngEgre ?></td>
                    
                     <?php 

                         $id = $listaCreditos[$i]->id;
                      ?>

                    </td> 
 
                    <td> 
                      
                     
     
                     <i class="fa fa-fw fa-edit"></i><?php   echo Html::linkAction("edit/$id", 'Editar este registro');

            ?>

                   


                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

</div>
<!-- /.row -->

<!-- /.row -->
<div class="row">

  <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>
</div>